name: Server/Api Docker Build and Push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: memquest-server

on:
  push:
    branches: ["main"]
    paths:
      - server/memoryquest_server/**
      - .github/workflows/agentic_memquest_server.yml

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_number }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./server/memoryquest_server
          file: ./server/memoryquest_server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ env.IMAGE_NAME }}
          cache-to: type=gha,scope=${{ env.IMAGE_NAME }},mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}